### ISSUE TITLE
[Feature Request] command line option to start minimized (system tray)

### ISSUE THREAD

**Issue by omega32** [diegojgb/WatchLog#1]
Hi, in most use cases, I don't think users will need to open the app window. Once they have the monitors and notifications set up.

As such, It would be nice to have an option to start the app in the tray.

And to simplify the implementation of the feature, it could just be a command line option (ex: `--minimized` or `-m`). Not exposed in the UI. As a bonus, this would give you the flexibility to start the app differently, depending on the situation.

**Comment by diegojgb** [comment]
Added in commit [7c0fe75](https://github.com/diegojgb/WatchLog/commit/7c0fe75837ea50ab56fffc17535462cb5a314a98)

You can now pass `--minimized` as a command line option.
